<form id="co-heared4us-form" action="">

<?php 

$_options = Mage::helper('heardreport')->getHeardFromList();

?>

	<select id="getvoice" name="getvoice" class="input-text required-entry">
        <option value="">Please Select</option>
		<?php foreach($_options as $_option): ?>
			<option value="<?php echo $_option ?>"><?php echo $_option ?></option>
		<?php endforeach; ?>
		<option id="getvoice-other" value="<?php echo $this->__('Other') ?>"><?php echo $this->__('Other') ?></option>
	</select>

</form>

<div class="buttons-set">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    
    <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    <button type="button" class="button" onclick="heared4us.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
    <span id="heared4us-please-wait" style="display:none;" class="opc-please-wait">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
    </span>
</div>

<div class="button-set">
    <div id="heared4us-buttons-container">
   
        <button type="button" class="button" onclick="heared4us.save();" style="display:none;"><span><?php echo $this->__('Continue') ?></span></button>

    </div>
</div>



<script type="text/javascript">
//<![CDATA[

var Heared4us = Class.create();
Heared4us.prototype = {
    initialize: function(form, saveUrl){
        this.form = form;
        if ($(this.form)) {
            $(this.form).observe('submit', function(event){this.save();Event.stop(event);}.bind(this));
        }
        this.saveUrl = saveUrl;
        this.onSave = this.nextStep.bindAsEventListener(this);
        this.onComplete = this.resetLoadWaiting.bindAsEventListener(this);
    },

    save: function(){
        if (checkout.loadWaiting!=false) return;

        var validator = new Validation(this.form);
        if (validator.validate()) {

            checkout.setLoadWaiting('heared4us');


            var request = new Ajax.Request(
                this.saveUrl,
                {
                    method: 'post',
                    onComplete: this.onComplete,
                    onSuccess: this.onSave,
                    onFailure: checkout.ajaxFailure.bind(checkout),
                    parameters: Form.serialize(this.form)
                }
            );
        }
    },

    resetLoadWaiting: function(transport){
        checkout.setLoadWaiting(false);
    },

    nextStep: function(transport){
        if (transport && transport.responseText){
            try{
                response = eval('(' + transport.responseText + ')');
            }
            catch (e) {
                response = {};
            }
        }

        if (response.error){
            if ((typeof response.message) == 'string') {
                alert(response.message);
            } else {
                if (window.billingRegionUpdater) {
                    billingRegionUpdater.update();
                }

                alert(response.message.join("\n"));
            }

            return false;
        }

        checkout.setStepResponse(response);
    }    
}

var heared4us = new Heared4us('co-heared4us-form', '<?php echo $this->getUrl('checkout/onepage/saveHeared4us') ?>');

//]]>
</script>
