<!--
/*////////////////////////////////////////////////////////////////////////////////
 \\\\\\\\\\\\\\\\\\\\\\\\\  FME QuickCheckout extension  \\\\\\\\\\\\\\\\\\\\\\\\\
 /////////////////////////////////////////////////////////////////////////////////
 \\\\\\\\\\\\\\\\\\\\\\\\\ NOTICE OF LICENSE\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
 ///////                                                                   ///////
 \\\\\\\ This source file is subject to the Open Software License (OSL 3.0)\\\\\\\
 ///////   that is bundled with this package in the file LICENSE.txt.      ///////
 \\\\\\\   It is also available through the world-wide-web at this URL:    \\\\\\\
 ///////          http://opensource.org/licenses/osl-3.0.php               ///////
 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
 ///////                      * @category   FME                            ///////
 \\\\\\\                      * @package    FME_QuickCheckout              \\\\\\\
 ///////    * @author     Malik Tahir Mehmood <malik.tahir786@gmail.com>   ///////
 \\\\\\\                                                                   \\\\\\\
 /////////////////////////////////////////////////////////////////////////////////
 \\* @copyright  Copyright 2010 © free-magentoextensions.com All right reserved\\\
 /////////////////////////////////////////////////////////////////////////////////
 */
-->

<dl class="sp-methods" id="checkout-payment-method-load">
                                    <?php if(Mage::getStoreConfig('fieldsmanager/general/enable') == 1){
                    echo $this->getfieldshtml(1);
                    }?>
<?php $i=0; foreach ($this->getMethods() as $_method): $_code = $_method->getCode(); ?>
    <dt>
    <?php if( sizeof($this->getMethods()) > 1 ): ?>
        <?php if($this->getSelectedMethodCode()=='' && $i==0): $i=1; ?>
            <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')" class="radio validate-one-required-by-name" />
        <?php else: ?>
            <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')" class="radio validate-one-required-by-name" />
        <?php endif; ?>
    <?php else: ?>
        <span><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" class="radio" /></span>
    <?php endif; ?>
        <label for="p_method_<?php echo $_code ?>"><?php echo $this->getMethodTitle($_method)?$this->getMethodTitle($_method):$_method->getTitle(); ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
    </dt>
    <?php if ($html = $this->getPaymentMethodFormHtml($_method)?$this->getPaymentMethodFormHtml($_method):$this->getChildHtml('payment.method.'.$_code)): ?>
    <dd>
        <?php echo $html; ?>
    </dd>
    <?php endif; ?>
<?php endforeach; ?>
                    <?php if(Mage::getStoreConfig('fieldsmanager/general/enable') == 1){
                    echo $this->getfieldshtml(2);
                    echo $this->getfieldshtml(3);
                    }?>
</dl>
<script type="text/javascript">
//<![CDATA[
payment.init();

if(document.getElementById('p_method_free')){
    document.getElementById('p_method_free').checked = true;
    document.getElementById('payment_form_authorizenet').style.display="none";
}
//]]>
</script>
<script type="text/javascript">
    //<![CDATA[
    var ShippingMethods_Loading_Text='<?php echo Mage::helper('quickcheckout')->getQuickCheckoutLoading('ship_method')?Mage::helper('quickcheckout')->getQuickCheckoutLoading('ship_method'):'Updating Shipping Method';?>';
        $$('#checkout-payment-method-load dt input').invoke('observe', 'click', function(event){payment.savePayment();});
    //]]>
</script>
